default: &default
  adapter: postgresql
  encoding: unicode
  username: urchmaney
  password: 123456
  host: 127.0.0.1

development:
  <<: *default
  database: facebook-on-rails

test:
  <<: *default
  database: facebook-on-rails_test
  