default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: facebook-on-rails1
  username: sam
  password: 123456
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: facebook-on-rails_test1
  username: sam
  password: 123456
  host: 127.0.0.1

production:
  <<: *default
  database: db/production.sqlite3
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: mini-facebook1
  username: sam
  password: 123456
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: mini-facebook_test1
  username: sam
  password: 123456
  host: 127.0.0.1

production:
  <<: *default
  database: db/production.sqlite3