default: &default
  adapter: postgresql
  encoding: unicode
  username: sam
  password: 123456
  host: 127.0.0.1
  # host: ''

development:
  <<: *default
  database: facebook-on-rails2

test:
  <<: *default
  database: facebook-on-rails_test
  