default: &default
  adapter: postgresql
  encoding: unicode
  username: sam
  password: 123456
  host: ''

development:
  <<: *default
  database: facebook-on-rails2

test:
  <<: *default
  database: facebook-on-rails_test
  